---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mt-configmap
data:
  HTTP_PORT: "8080"
  HTTPS_PORT: "8443"
...
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
data:
  index.html:
     <!DOCTYPE html>
     <html>
     <head>
     <title>Netology homework-08</title>
     <body>
     <h1>Welcome to Netology!</h1><br>
     <h2>It is Homework-08!</h1>
     </body>
     </html>
...
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-nginx-multitool
  labels:
    app: nginx-multitool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-multitool
  template:
    metadata:
      labels:
        app: nginx-multitool
    spec:
      containers:
      - name: multitool
        image: wbitt/network-multitool
        command: ["sh", "-c", "while true; do sleep 3600; done"]
        envFrom:
          - configMapRef:
              name: mt-configmap
        ports:
        - containerPort: 8080
          name: mt-http
        - containerPort: 8443
          name: mt-https
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /usr/share/nginx/html/index.html
          subPath: index.html
          name: nginx-conf
      volumes:
      - name: nginx-conf
        configMap:
          name: nginx-configmap
...
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-multitool-service
  namespace: default
spec:
  selector:
    app: nginx-multitool
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
...