apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: multitool-daemonset
  namespace: default
spec:
  selector:
    matchLabels:
      app: multitool
  template:
    metadata:
      labels:
        app: multitool
    spec:
      containers:
        - name: multitool
          image: wbitt/network-multitool
          volumeMounts:
            - name: varlog
              mountPath: /var/log/nodelog
      volumes:
        - name: varlog
          hostPath:
            path: /var/log