apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-multitool-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox-multitool
  template:
    metadata:
      labels:
        app: busybox-multitool
    spec:
      containers:
        - name: busybox
          image: busybox
          command: ['/bin/sh']
          args:
            ['-c', 'while true; do echo $(date) >> /data/shared-file.txt; sleep 10; done',]
          volumeMounts:
            - name: shared-data
              mountPath: /data
        - name: multitool
          image: wbitt/network-multitool:latest
          command: ['/bin/sh']
          args:
            ['-c', 'while true; do cat /data/shared-file.txt; sleep 10; done']
          volumeMounts:
            - name: shared-data
              mountPath: /data
      volumes:
        - name: shared-data
          emptyDir: {}